// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/chaos/v1alpha1.ChaosPod":       schema_pkg_apis_chaos_v1alpha1_ChaosPod(ref),
		"./pkg/apis/chaos/v1alpha1.ChaosPodSpec":   schema_pkg_apis_chaos_v1alpha1_ChaosPodSpec(ref),
		"./pkg/apis/chaos/v1alpha1.ChaosPodStatus": schema_pkg_apis_chaos_v1alpha1_ChaosPodStatus(ref),
	}
}

func schema_pkg_apis_chaos_v1alpha1_ChaosPod(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChaosPod is the Schema for the chaospods API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/chaos/v1alpha1.ChaosPodSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/chaos/v1alpha1.ChaosPodStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/chaos/v1alpha1.ChaosPodSpec", "./pkg/apis/chaos/v1alpha1.ChaosPodStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_chaos_v1alpha1_ChaosPodSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChaosPodSpec defines the desired state of ChaosPod",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"prefixToKill": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"checkEverySecond": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
				},
				Required: []string{"prefixToKill"},
			},
		},
	}
}

func schema_pkg_apis_chaos_v1alpha1_ChaosPodStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChaosPodStatus defines the observed state of ChaosPod",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"killedPodNames": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"killedPodNames"},
			},
		},
	}
}
