apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordered-chaos-monkey-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ordered-chaos-monkey-operator
  template:
    metadata:
      labels:
        name: ordered-chaos-monkey-operator
    spec:
      serviceAccountName: ordered-chaos-monkey-operator
      containers:
        - name: ordered-chaos-monkey-operator
          # Replace this with the built image name
          image: dxjoke/ordered-chaos-monkey-operator:v0.0.3
          command:
          - ordered-chaos-monkey-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ordered-chaos-monkey-operator"
